- hosts: all
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest

  - name: Start httpd
    systemd:
      name: httpd
      state: started
      enabled: yes

  - name: Install unzip
    yum:
      name: unzip
      state: latest

  - name: Extract a file
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page274/initio.zip
      dest: /var/www/html
      remote_src: yes

  - name: Disable SELinux
    selinux:
      state: disabled
